# Generated by Django 5.0.3 on 2024-04-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_age_profile_created_at_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, '기타'), (1, '남성'), (2, '여성')]),
        ),
    ]
