# Generated by Django 5.0.3 on 2024-04-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
