# Generated by Django 5.0.3 on 2024-04-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtiresponse',
            old_name='MBTIResult',
            new_name='mbtiresult',
        ),
    ]
